# R Community Diversity & Inclusion - Agenda 2019-11-04

Welcome to the [R Consortium Diversity and Inclusion Project](https://www.r-consortium.org/projects/r-community-diversity-and-inclusion)!

Today's agenda:

+ Welcome, overview, & helpful links
+ Introductions
+ Working Groups updates 

Present: Samantha Toet, Joe Rickert, Kevin O'Brien, Sydeaka Watson, Kathering Simeon, Shelmith Kariuki, Admadou, Gwynn Sturdevant

## Helpful Links

Work tracked on Github: https://github.com/RConsortium/RCDI-WG

Member Directory: https://docs.google.com/spreadsheets/d/17ymeWiOPfNtkCzVYqbBYMoZ46E-jDIMDnIPINMKy334/edit?usp=sharing

## Announcements and Group Updates

+ We've been voted a [Top Level Project](https://www.r-consortium.org/projects)!🎉 
+ Recruitment of new members — please to reach out to other people in the community who might be interested in participating. Please RT announcements on social media. 
+ 2020 budget submitted to RConsortium - should have updates next meeting

# Working Groups

### Organization of the Revised Code of Conduct for Events

(https://github.com/RConsortium/RCDI-WG/blob/master/conduct/code-of-conduct.md; Led by Joe Rickert, Gabriela de Quieroz, and Samantha Toet)

Discussion about summarization (similarly to Carpentries CoC https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html), distribution, and enforcement (possibly in organizer’s checklist?). 

Joe and Samantha working on opening statement about commitment to diversity and subsequent categorization.

How can we share it with more of the community? We’ll start with social media. 

### Conference Best Practices Checklist/Badges

(https://github.com/RConsortium/RCDI-WG/blob/master/outputs/conferencebestpractices.md, Led by Samantha Toet & Noa Tamir)

Google Sheet listing and categorizing all items: https://docs.google.com/spreadsheets/d/1CLRbwqNAEvG8-yeoM0AJsBqXU7Lot3jGFPtNz7zUfYU/edit?usp=sharing. 

Discussing partnership with [NumFocus](https://numfocus.org/programs/diversity-inclusion). Kevin to reach out to Bojan Bozic and invite them to our meetings. Sam to start drafting partnership proposal. 

### Guidelines for Recruitment of Diverse Speakers

(https://docs.google.com/document/d/13FAb4UwUD4fBhlUi8uRJ9fPWur2cqXT4017nV3J1P3Y/edit; Led by Sydeaka Watson and Derrick Kearney)

Updated notes from pre-meeting interviews with Danielle Robinson, Lorena Mesa, and Naomi Cedar. See above Google Doc.

Proposing new dates for in-meeting interviews. March or April 2020. Keeping format previously discussed: 20 minute conversations, with 15 minutes between organizer and moderator, then 5 minutes conversation / questions from everyone.

New ideas seen at conferences: first time speaker track at PyCon Limerick Ireland

### R in Africa

(Led by Shelmith Kariuki, Dennis Irorere)

Update on local R user groups:

+ Many organisers struggling to find venues. 
+ Shelmith and Dennis busy helping organisers apply for R consortium funding

Exploring the idea of remote conference hubs. 

2020 Conference in Nigeria (at least 6 active groups) - researching venue, would be in French

Team up with SatRdays? https://abidjan2020.satrdays.org/

Allocation of RStudio funds? ST, HW, and SK to discuss how money will be distributed and guidelines for use (similar to RUGs requirements). JR to raise this issue with the R Consortium.

### Participant Diversity - Visa Project

(Kevin O’Brien, Richard Ngamita)

How can organizers support difficult travel and Visa needs for international participants and diversity scholars? 

Suggestions: extend timeline, work with participants on an individual need-by-need basis, work with embassies, provide more verified information and documentation. 

Look at Visa situation in African regions (East, West). Break out into separate countries? US and EU.

Looking for additional participants to help out with this. 

### Additional Topics

RStudio::conf watch parties?

Publishing of a Conf Accessibility Plan - could this be a separate funded working group?

+ Website (screen readers)
+ ADA compliant

How do we help smaller conferences (i.e not UseR! or rstudio::conf) implement this?

Livestream training sessions? Larger investment, but should be considered for future events?

Birds of a Feather at conf

Fully remote events? Negates the value of in-person experiences. Pay for part of the live streaming as an add-on option 

### Next Meeting

Mon, Dec 2nd, 7:00pm to 8:00pm (GMT +00:00) UTC




