# R Community Diversity & Inclusion - Agenda 2021-01-04

[R Consortium Diversity and Inclusion Project](https://www.r-consortium.org/projects/r-community-diversity-and-inclusion)

Past meeting notes can be found here: https://github.com/RConsortium/RCDI-WG

## Present

- gwynn sturdevant
- Samantha Toet
- Joe Rickert
- Kevin O'Brien
- Sailesh Vizzu
- Dennis Irorere
- Shelmith Kariuki
- Derrick Kearney

## Agenda

Revisit 2021 Meeting Timing - is 7pm UTC still a good time for everyone? 

  - Doodle poll: https://doodle.com/poll/fif3dauwgq29mwsb?utm_source=poll&utm_medium=link
  - Need to reach out to Brian at LinuxFoundation for access to update the calendar

Goals of our working group - encourage people/organizations to:

  - Join R Consortium
  - Participate in events 
  - Consider diverse representation at events/programs in primary organizing efforts 
  - Recruit speakers
  - Partnering with other organizations to intentionally organize/develop events
  - Supporting mentorship and guidance, obtaining resources for underrepresented groups
  - ^^ Should be put on Github README and website 
  
2021 Conference Support: 2 R Consortium conferences R/Medicine and R/Pharma, plus UseR!2021
  
  - How are we currently involved in this process? 
    - What can we do to improve the virtual experience? 	
    - Can we help them find speakers? Suggest speakers now - Ruha Benjamin
    - What does diversity look like at these conferences? 
    - Are we involved with CoC?
    - Are we involved with Diversity Scholarship programs? 
    - ST - to get answers to the above should we invite organizers to advisory meeting? Invite to RCDI? 
    - DK -  ^^ that could be part of promo/benefits?
  
  - What can these conferences do to be more inclusive of non-US time zones?
    - Obtaining data and/or metrics from R consortium programming and events
    - Can we get a needs assessment from community members in underrepresented groups?

WhyR? World Support - Kevin O'Brien

  - A series of short 10-15 minute interviews with R users around the world with the goal of motivating their peers to contribute talks to virtual conferences
  - Short, casual community-based chats
  
2021 Event Calendar 

- Community calendar that lists all global R community events. Users can search events, add their own, and find speakers and co-organizers. 
- Will be linked on RCDI RConsortium page 
- Committee to start meeting and organizing next month 
  
[Code of Conduct Guide - Draft](https://docs.google.com/document/d/1fCx5zfANmteeMDuLzp1vIlZUEstbsFLwE7qXaM0cjzo/edit?usp=sharing) 

- This is a “how to” guide for organizers to create a code of conduct that is unique to their event in regards to behavior, communication, and enforceability both in the digital and in-person space. 
- As most events turn virtual, there is a new need to address how a CoC can be adapted to fit an online event.
- Used as basis for [rstudio::global(2021) Code of Conduct](https://global.rstudio.com/student/page/40000?navlink=true) 


## Next meeting: Monday, January  7th, at 7:00pm UTC 